# Generated by Django 5.2.5 on 2025-11-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HODRegistrationRequest',
        ),
    ]
