# Generated by Django 5.2.5 on 2025-11-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_delete_hodregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/admin_images/'),
        ),
    ]
