# Generated by Django 5.2.5 on 2025-11-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_user_email_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodregistrationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('retired', 'Retired')], default='pending', max_length=10),
        ),
    ]
