# Generated by Django 5.2.5 on 2025-11-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_hodregistrationrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin'), ('hod', 'HOD'), ('principal', 'Principal')], default='student', max_length=20),
        ),
    ]
