# Generated by Django 5.2.5 on 2025-11-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        ('instructors', '0002_delete_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
    ]
