# Generated by Django 5.2.5 on 2025-10-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='student_images/default.jpg', null=True, upload_to='student_images/'),
        ),
    ]
