# Generated by Django 5.2.5 on 2025-11-12 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOD',
        ),
    ]
