# Generated by Django 5.2.5 on 2025-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('instructors', '0002_delete_hod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-marked_at']},
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='attendanceeditpermission',
            name='proposed_status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceeditpermission',
            unique_together={('instructor', 'attendance', 'status')},
        ),
    ]
