# Generated by Django 5.2.5 on 2025-10-21 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='fee',
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='department',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='semester',
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='FeeStructure',
        ),
    ]
